# Generated by Django 4.2.5 on 2023-12-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='threshold_humidity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='threshold_temperature',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='threshold_water_quality',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
